name: Profile stats

on:
  push:
    branches: [ main ]
  schedule:
      - cron: '0 */20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Calcutta
          repositories_forks: yes
          plugin_followup: yes
          plugin_habits: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_languages: yes
          plugin_achievements_limit: 0
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 15747757
          plugin_stackoverflow_sections: ''
          plugin_stackoverflow_lines: 0
          plugin_stackoverflow_limit: 1
          plugin_languages_skipped: conan-center-index
          plugin_isocalendar: yes
